### ISSUE TITLE
Grundlayout

### ISSUE THREAD

**Issue by capoaira** [capoaira/liga-tabelle#7]
- [x] Farbkonzept
- [x] Header/Menü
- [x] Footer

ToDo:
- [ ] Footer hoch ziehen mit css
```css
#content {
    min-height: calc(100vh - headerhöhe)
}
```

**Comment by capoaira** [comment]
- [ ] Footer hoch ziehen mit css

```css
#content {
    min-height: calc(100vh - headerhöhe)
}
```
